name: 'lakehouse_dbt'
version: '1.0.0'
config-version: 2

profile: 'nyc_taxi_lakehouse'

model-paths: ["models"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  lakehouse_dbt:
    silver:
      +schema: data_project_silver
      +materialized: incremental
    gold:
      +schema: data_project_gold
      +materialized: table